### ISSUE TITLE
Meeting frequency

### ISSUE THREAD

**Issue by Qard** [nodejs/tracing-wg#1]
We should decide on a regular frequency for working group meetings to ensure we are making progress.

**Comment by mikeal** [comment]
A lot of us will have issues meeting next week because of Node Summit so why don't we schedule one for the week after use that to gauge how much agenda we're getting bi-weekly.

**Comment by Qard** [comment]
Yep, I suspected next week would be hard. I don't expect there'll be enough to talk about to have meetings weekly--not yet, anyway.
