### ISSUE TITLE
NodeConf

### ISSUE THREAD

**Issue by Qard** [nodejs/tracing-wg#14]
Hey all, I'd like to get the ball rolling on tracing. Who's going to be at NodeConf? Perhaps we should take some time to chat about tracing?

**Comment by ofrobots** [comment]
Unfortunately, I won't be at NodeConf. Otherwise, I would have been keen to participate.

**Comment by trevnorris** [comment]
Also won't be attending. Please keep notes on any discussions/decisions made so we can chime in afterwards.

**Comment by Qard** [comment]
Will do.

**Comment by Qard** [comment]
There wasn't a whole lot of tracing discussion. Most of the people currently working on it were not present, so there was little to talk about.

**Comment by wraithan** [comment]
I'll be at summit and cascadia, if others will be at either of those
