### ISSUE TITLE
Is this group still active? <eom>

### ISSUE THREAD

**Issue by yunong** [nodejs/tracing-wg#16]

**Comment by trevnorris** [comment]
Yes. Initial discussions have been slow, but they are happening and action will be accelerating. See https://github.com/nodejs/tracing-wg/issues/15 for further information.

**Comment by Qard** [comment]
Tracing is a hard problem that takes time to deal with, and most people involved in this working group are busy with their own things. Google has been making gradual progress on their own tracing tools for V8, and I've been working to keep the channel open to discuss integrating that work. Trevor has been working on async_wrap, but he's busy with other things, so development is a bit slow.

Unfortunately, few companies consider tracing to be a critical need of node. It's mostly just the few of us that work at APM providers and some other casually interested people pushing this along. I hope that as we start to deliver some of the things we've been working on, more people will start to gain an interest in contributing to the effort.
