### ISSUE TITLE
Current State of Tracing

### ISSUE THREAD

**Issue by matthewloring** [nodejs/tracing-wg#18]
Hi All,

With the collaborator summit coming up, I wanted to send out a list of previous discussions/resources/projects relate to the current state of tracing. The idea was to gather the links in one place in case others want to brush up on previous discussions. This is not meant to be an exhaustive list, so if others have materials that would be good to review, please post them as comments.

1. Notes from the tracing summit in 2014:

 - https://gist.github.com/groundwater/942dad5c0c4cfae21af9

2. Notes on the Chromium/V8 approach to tracing:

 - https://github.com/nodejs/io.js/issues/671#issuecomment-73191538

 The rest of this issue also has some perspectives on tracing.

3. Ideas / proposals

 - https://github.com/Qard/stacks-concept
 - https://github.com/brycebaril/transaction-tracer

**Comment by Qard** [comment]
Thanks for compiling this list! I'd also add [async-wrap](http://blog.trevnorris.com/2015/02/asyncwrap-tutorial-introduction.html), although it is still a work-in-progress.

**Comment by trevnorris** [comment]
Need to write an updated blog post. The API has changed to make life easier.

**Comment by AndreasMadsen** [comment]
The collaborator summit is over, closing this.
