### ISSUE TITLE
Help needed with organizing and facilitating

### ISSUE THREAD

**Issue by Qard** [nodejs/tracing-wg#19]
When I started the tracing working group, I basically took on the organizer/facilitator role myself, out of necessity. I don't feel I'm doing a great job of keeping us on track though. Is anyone else able to help out or take over that role?

**Comment by pmuellr** [comment]
I've been meaning to get involved with a NF working group, and tracing is an interesting topic for me so ... I'll volunteer myself.  

I will admit to being a bit of a n00b on the current tracing story, but to happy to get  some calls organized, etc, to start with.

**Comment by Qard** [comment]
That's fine. The current state is a bit nebulous anyway.

There's some Google work happening to pull out the Chrome dev tools from blink, making them easier to use with node. There's also some work happening (albeit slowly) on async_wrap and designing a generic native tracing interface, so we can maybe do dtrace/lttng/etw support outside of core some day.

**Comment by lucamaraschi** [comment]
It looks pretty inactive but at the same time one of the crucial components of the node.js ecosystem...how can we help resuscitate the conversations and get the WG back on track?
@yunong do you also agree?

**Comment by yunong** [comment]
Yeah, it'd be great to get this kick started. How about we schedule a meeting to figure out the state of things?

**Comment by Qard** [comment]
I think a big challenge we have is that, while the work we are trying to do is very important, it's also a _ton_ of work. I think we need a meeting to discuss how to make some more bite-sized tasks and get people started on making some progress.

**Comment by pmuellr** [comment]
I've been fairly swamped lately, but have an entry on my calendar for next week to get a meeting scheduled.  @lucamaraschi seems to be in Europe, @Qard on the west coastLuca is in Europe, so we could do a 5pm Europe, 9am Pacific call.  Any other time zones beyond, maybe Rodd Vagg?

**Comment by lucamaraschi** [comment]
I am more than happy to help where I can...next week I will be in BKK but next friday I will be back in AMS so 5pm local time looks great for me!

**Comment by lucamaraschi** [comment]
@Qard, @pmuellr, @yunong, @rvagg  shall we create a Doodle pool and check when we can meet and get this topic moving again?

**Comment by bnoordhuis** [comment]
Are you sending out an invite to all WG members? Because, time permitting, I'd like to join as well.

**Comment by lucamaraschi** [comment]
@bnoordhuis I can send out a Doodle today so that we can aim to it for end of next week maybe ;-)

**Comment by lucamaraschi** [comment]
I think a Doodle is not going to work efficiently...is it an idea to aim for the 09/25/2015 at 9am Pacific?

**Comment by bnoordhuis** [comment]
That's exactly dinner time for me.  An hour earlier or later (preferably earlier) would be better.

**Comment by lucamaraschi** [comment]
Shall we then do 8am Pacific? 
How is anybody else feeling about this time proposal?

**Comment by pmuellr** [comment]
Works for me.

[world time link](http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Tracing+WG&iso=20150925T08&p1=224&ah=1) for 8am Pacific

**Comment by yunong** [comment]
8 am is good for me.

**Comment by Qard** [comment]
They've invented an 8AM now? :trollface: 

Seriously though, I can be up for that, if that time works for everyone else.

We should put together an issue to decide on agenda and such.

**Comment by pmuellr** [comment]
I created an issue - https://github.com/nodejs/tracing-wg/issues/21

@Qard @yunong send me your emails so I can add to a goog doc / hangout

How do we advertise the meeting?
