### ISSUE TITLE
add docs directory to repo

### ISSUE THREAD

**Issue by pmuellr** [nodejs/tracing-wg#22]
There's enough meaty information today collected in both the meetings and issues here, that I think it would be useful to create some documentation on the various components that have been discussed so far.  That would include:

* AsyncWrap
* v8-tracing
* platform-specific tracing (eg DTrace, LTTng, ETW for Windows)
* perf-events (from Yunong)

I would expect this to be rather fluid, as we've not settled on any stories for anything yet.  So I'd expect lots of updates and evolution.

We could also do this in the wiki, but I find the wiki a bit harder to deal with.

**Comment by Qard** [comment]
:+1: The wiki feature is not great. Putting this stuff in the repo would probably be better.
