### ISSUE TITLE
Want to Join

### ISSUE THREAD

**Issue by arunoda** [nodejs/tracing-wg#3]
Hi,

I'm running the [kadira.io](https://kadira.io), a performance monitoring service for Meteor. As part of that, we built a our own Flamegraph viewer which we think best for finding issues. I really like to join this discussion and actively contribute.

Here some info about our CPU profiler: https://kadira.io/academy/meteor-cpu-profiling/
Here's a live demo: http://goo.gl/hdVOOl

**Comment by bnoordhuis** [comment]
You're more than welcome.  I believe the next meeting is to be scheduled for next week.  Maybe leave a comment on #1 with times and days/dates that work for you.

**Comment by arunoda** [comment]
Awesome.
I'm normally flexible with times.
