### ISSUE TITLE
WG Meeting Week of February 19th on `trace_event`

### ISSUE THREAD

**Issue by mikeal** [nodejs/tracing-wg#4]
We should have a working group meeting this week, there's a lot to discuss but because we have so many people I think that we're going to have to limit the meeting in scope and ask that people unfamiliar with the topic watch the feed rather than get on the hangout since space on hangouts-on-air is limited.

I think we should discuss v8/chrome's `trace_event` and how this can be leveraged by `iojs`. In particular, I've heard people wondering if we might actually be able to replace `AsyncWrap` with trace events which would make it easier to write more unified tooling. If changes to the debugging plan this big are being considered we should shake them out now :)

Off the top of my head I think we need @natduca @ofrobots @trevnorris and @thlorenz and probably others.

**Comment by arunoda** [comment]
I'm happy to watch the feed :)

**Comment by rmg** [comment]
I don't think I have anything to offer on this one, and I can always feed my input through @sam-github or @piscisaureus if I hear something on the youtube stream.

**Comment by thekemkid** [comment]
I'll watch the feed. :)

**Comment by bnoordhuis** [comment]
I'll try to join but I'm moving next week and I may not have a working internet connection on the 19th yet.

**Comment by natduca** [comment]
Happy to join.

**Comment by thlorenz** [comment]
We should get Ali from Google (don't remember his last name or github handle) into the discussion  as well as he has expressed interest in helping us adopt the v8 tracing format.
Some of you (i.e. @mikeal) may have talked to him at NodeSummit and remember his handle to summon him in here.

I myself would be available any day of the week and early Friday for a meeting.

**Comment by thlorenz** [comment]
Also linking in @natduca's very [detailed notes](https://github.com/iojs/io.js/issues/671#issuecomment-73191538) regarding tracing in chromium since I believe that some points in there should become part of the discussion.

**Comment by ofrobots** [comment]
I'll be happy to join. (Hi Thorsten!)

On Fri, Feb 13, 2015 at 9:09 AM, Thorsten Lorenz <notifications@github.com>
wrote:

> Also linking in @natduca <https://github.com/natduca>'s very detailed
> notes <https://github.com/iojs/io.js/issues/671#issuecomment-73191538>
> regarding tracing in chromium since I believe that some points in there
> should become part of the discussion.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/iojs/tracing-wg/issues/4#issuecomment-74288501>.
>



-- 
Ali

**Comment by thlorenz** [comment]
Awesome @ofrobots, glad to have you :)

**Comment by piscisaureus** [comment]
>  In particular, I've heard people wondering if we might actually be able to replace AsyncWrap with trace events 

That sounds a bit strange to me since AsyncWrap and tracing aren't really related. Potentially you're thinking about replacing @trevnorris' tracing support?

**Comment by mikeal** [comment]
@piscisaureus I think @piscisaureus and @ofrobots can probably explain it better.

**Comment by sam-github** [comment]
I'd like to be involved, I'm working on these areas for StrongLoop ATM.

**Comment by sam-github** [comment]
Also, is there a target day? Later in the week would work better for me, morning would probably help cross time zones from North American pacific coast through Europe.

**Comment by kraman** [comment]
Hi, I would like to join this WG as well. I am working with Sam on the same areas within StrongLoop. Thanks

**Comment by mikeal** [comment]
Doodle for finding the best time on Thursday. http://doodle.com/yds5u6ns86t85tuu

**Comment by trevnorris** [comment]
> I've heard people wondering if we might actually be able to replace AsyncWrap with trace events which would make it easier to write more unified tooling

You can't just replace `AsyncWrap`. It's part of how the asynchronous class structure is created. All that you could do is remove the user exposed hooks. Though the advantage to `AsyncWrap` is that it is VM independent.

**Comment by mikeal** [comment]
replace was probably the wrong way to put it, it was more like "feed asyncwrap events in to trace_event"

**Comment by Qard** [comment]
I put myself up for any time, though I might just lurk in IRC if it gets too full.

I'm not sure how much I have to contribute to the conversation anyway. I've only just recently started digging into tracing the native side.

**Comment by mikeal** [comment]
Doodle is closed, Thu 2/19/15 2:00 PM – 3:00 PM PST.

**Comment by mikeal** [comment]
Participation link for WG meeting today: https://plus.google.com/hangouts/_/hoaevent/AP36tYfCdqP069ksasAoWqzK5gGpvS7T0BVhOWoCJxS9Ay8wtiKEJw?authuser=0&eid=101986715696875566237&hl=en-GB

Event link for people watching: https://plus.google.com/b/101986715696875566237/events/c791vkvvdldnvf14t08vcfa8hv4

Agenda and Notes
https://docs.google.com/document/d/1_ApOMt03xHVkaGpTEPMDIrtkjXOzg3Hh4ZcyfhvMHx4/edit?usp=sharing

Please add things to the Agenda, it is very slim right now.
