### ISSUE TITLE
Possibility for data loss Async UIDs?

### ISSUE THREAD

**Issue by mike-kaufman** [nodejs/tracing-wg#44]
I'm looking through the AsyncWrap code, and it appears that 64-bit signed int values are being cast to 32-bit signed int values [here](https://github.com/nodejs/node/blob/master/src/async-wrap-inl.h#l43), [here](https://github.com/nodejs/node/blob/master/src/async-wrap.cc#l201) and [here](https://github.com/nodejs/node/blob/master/src/async-wrap-inl.h#l75).

A few questions:

1)  Am I reading this correctly? 
2)  Is there an alternative here?  I don't immediately see how to seed a V8::Number with a 64-bit int.
3)  Is 32 bits enough "space" to maintain a monotonically increasing set of unique IDs?  A process running continuously for 30 days, and consuming 1657 async events per second would exhaust this space & subsequent casts would overlap with previously issued IDs. 

Thanks,

Mike

**Comment by trevnorris** [comment]
No it's not correct, and I know it's a problem. I have a fix in the pipeline.

**Comment by trevnorris** [comment]
Fixed here https://github.com/nodejs/node/pull/7096
