### ISSUE TITLE
Next Tracing WG meeting? Thursday next week? (The 12th March)

### ISSUE THREAD

**Issue by thekemkid** [nodejs/tracing-wg#6]
Its been a while since we had one. I want to do some work on the tracing hook area, but haven't touched it since the v8 trace_event thing came out.

**Comment by mikeal** [comment]
I think we've been waiting on the trace_event stuff to land before doing another one but the unified system hook stuff can be done without waiting for that.

**Comment by Qard** [comment]
Yep, that's pretty much it. We could use some further discussion on the unified tracing and async_wrap stuff though.

**Comment by thekemkid** [comment]
Well then should we just wait for it to land? We can hold off until it lands. :)

**Comment by mikeal** [comment]
Someone needs to write the unified tracing endpoint, could be you ;)

**Comment by thekemkid** [comment]
I started work on it on my fork, but got stuck with the ECW stuff... Granted, I started at 4am after a meetup... :stuck_out_tongue: 

I should get back to it again. :smile:

**Comment by Qard** [comment]
Another thing to add to the agenda: a polyfill for async_wrap, similar to what https://github.com/othiym23/async-listener is for AsyncListener. I believe @othiym23 may already be looking into it. I want to get something built for that and get continuation-local-storage updated. Mostly my interest is to clarify what work is being done and who will be responsible for what.

**Comment by hayes** [comment]
I would be interested in helping with a polyfill, I have not spent enough time with async_wrap yet to know what the problem areas will be.

**Comment by bnoordhuis** [comment]
What time (UTC / CET) would the call be?  Also, has anyone written up a proposal on unified tracing yet?

**Comment by Qard** [comment]
There are several ideas that were presented here: https://github.com/iojs/io.js/issues/729. No exact implementation has been defined though.

I put together a doodle for the last half of next week. It might be a bit late to coordinate something for this week. http://doodle.com/4d2g2s359qw7ibbv

**Comment by thekemkid** [comment]
I've looked into doing the unified trace area as I described in my gist, but the ecw stuff is messy compared to the others, I'll muddle around with it some more by that meeting https://gist.github.com/thekemkid/c51ed25eb3a5a603cb7e

**Comment by Qard** [comment]
@natduca @ofrobots You have anything new to say yet on trace_event?

@trevnorris How about async_wrap? What still needs to be done there?

**Comment by ofrobots** [comment]
Here's the first CL from Fadi on getting trace-event into V8: https://codereview.chromium.org/988893003/. We are hoping that we can get all the CLs in March. I hoping to start playing with trace_event too, but haven't gotten an opportunity to do that yet.

**Comment by trevnorris** [comment]
@Qard What still needs to get done:

* Integrate with the JS of timers and `nextTick()`
* Integrate with Promises (depends on V8)
* Allow PROVIDER filters
* Pass the PROVIDER type of the call as argument to callbacks
* Create C++ callbacks for native hooks

That's just off the top of my head.

**Comment by AndreasMadsen** [comment]
@Qard @trevnorris I would like to add:

* Allow try/catch/finally like error handing
* Add tests cases. Will particularly be useful for the guys writing a polyfill

**Comment by trevnorris** [comment]
@AndreasMadsen Agreed on the tests. My original error handling code would allow intercepting the bubbled exception before it hit `unhandledException`. This would also allow viewing the stack from the entry point of the async call. I'm fine with re-implementing that.

**Comment by AndreasMadsen** [comment]
@trevnorris Yes that is exactly what I meant. Right now I'm monkey patching `process._fatalException` to get around it.

**Comment by trevnorris** [comment]
@AndreasMadsen glad we're on the same page. I've added that to my list.

**Comment by Qard** [comment]
It looks like everyone is good for Thursday or Friday at 1PM. If anyone else wants in on this and hasn't submitted times already, please do so now. If nothing changes in the next 24 hours, I'm going with Friday at 1PM.

**Comment by bnoordhuis** [comment]
@Qard 1 PM in what timezone?  I'm somewhat suspicious of that doodle taking my timezone into account.

**Comment by Qard** [comment]
@bnoordhuis PST.

**Comment by thekemkid** [comment]
@qard some stuff is after coming up for me and I _might_ not be able to make it, but hopefully I can put together a gist of any info I have on unified tracing (Not much right now, but some). Sorry about this.

**Comment by wraithan** [comment]
Added myself to the poll. Thursday is mostly shot for me, but Friday works.

**Comment by Qard** [comment]
Friday at 1PM it is.

Agenda:
- async_wrap polyfill (ownership, browser support, etc)
- unified tracing progress
- trace_event?

Anyone have anything further to add to the agenda?

**Comment by trevnorris** [comment]
1PM PDT?

**Comment by bnoordhuis** [comment]
/me changes his 'are you coming?' status to 'maybe'

**Comment by Qard** [comment]
@trevnorris Yes. PDT/PST, same thing right now.

**Comment by trevnorris** [comment]
I'm AFK ATM and can't find the link. I'll jump on if I can.

**Comment by othiym23** [comment]
@trevnorris https://plus.google.com/hangouts/_/hoaevent/AP36tYcMH6Mv9LtAoe101G89VsMmQXgZ2eKBeLtn3MOiHVUdWbRf7w?authuser=0&hl=en is the participant link for the Hangout. Things are sort of shambolic here so far, but we'd love to have your input.

**Comment by trevnorris** [comment]
@othiym23 And hangout fail for the phone. Apologies for not being on today.

**Comment by othiym23** [comment]
@trevnorris We missed you. ;) See [the notes](https://docs.google.com/document/d/1P7Sn5qhJldaU6uLOu_Uk_wEpmAzQE624wEtAURQtAq4/edit) for some of the open topics we'd love to discuss with you.

**Comment by sam-github** [comment]
Is there a link to the discussion?

**Comment by trevnorris** [comment]
@othiym23 thanks. i'll look at the issues that have been created. Also left a couple notes on the doc.
